### ISSUE TITLE
Sea Serpent causing my server to crash

### ISSUE THREAD

**Issue by Rattle189** [ArkTechMC/IceAndFire-Fabric#31] opened 2024-08-13 01:33 UTC
### What had happened?
The server has crashed because a Sea Serpent has attempted to do a melee attack, at least that's what the crash report says.

*What you have done and what happen*
Nothing, players are simply exploring and the server crashed out of the blue.

### Mod Version (Include dependencies)
Fabric API 0.92.2+1.20.1
Ice And Fire 0.5.1
Jupiter 0.4.1
Uranus 1.6

~~x.y.z~~

### Mod Loader Version

Fabric 0.15.11

### Game Log
[crash-2024-08-13_02.24.52-server.txt](https://github.com/user-attachments/files/16593350/crash-2024-08-13_02.24.52-server.txt)

### Checklist

- [x] I don't install Optifine
- [x] I have installed other mods

**Comment by IAFEnvoy** [comment] 2024-08-13 01:47
known issue caused by a conflict with other mods. has been fixed in alpha version which can download in my discord

**Closed by IAFEnvoy** 2024-08-13 01:47 UTC
