### ISSUE TITLE
Game Menu "Burns into screen" when custom background is disabled.

### ISSUE THREAD

**Issue by ZoeyTheDeer** [ArkTechMC/IceAndFire-Fabric#14] opened 2024-06-27 21:29 UTC
Version: 0.1.1  (Release date: 6/24/2024)

When you disable the custom background through config file, all menu's upon launch will have a "additive" or "burning" effect. Good way to describe this is a bugged Windows screen where a error message leaves a "trail" of itself, stamping itself repeatedly. This includes modded menu's such as Create, mod menu, and mod config. Title splash text is the most visible issue right off the bat as it creates a blur of every frame it covers. I also found that while the Create mod panorama in the settings is stable, it still imprints when leaving the screen. This odd effect continues across any edition to the menu's such as "Bounce" title mod, Essentials, and Custom Player Model.

The modpack I have thrown it into did not suffer this issue before this version, and through a LOT of experimenting, no other mod was causing it. Could not find any reference to this mod within the output log, neither warning or error was thrown regarding this bug. Stays persistent with loaded/unloaded resource packs as well.

Originally, I thought the solution would be to backtrack the verson, but I believe there is something much deeper going on with another mod that I simply have yet to figure out. I have attempted to backtrack every mod that updated the same day, but it seems to consist between versions now (0.1 and 0.1.1)

Steps to reproduce:
1. Set custom background in config to 'false'
2. Launch game through curseforge

Expected Result:
Game opens normally, menu is the default panorama (or custom if resource pack is involved)

Actual Result:
All menu's cause a burning/additive effect, constantly imprinting on any changes to the menu.

Solution:
Enable Custom Menu. 

![Capture](https://github.com/ArkTechMC/IceAndFire-Fabric/assets/84168642/4a087da1-575c-448a-ba79-5425b3237f15)

**Comment by IAFEnvoy** [comment] 2024-06-28 00:18
This is caused by a wrong invoke to the background renderer. It has been fixed in previous push.

**Closed by IAFEnvoy** 2024-06-28 00:18 UTC
Labels: bug, Fixed
